module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    '../../packages/ui/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#e9bcb6",
        "secondary-fixed": "#ebdcff",
        "primary-container": "#e50914",
        "tertiary-container": "#0072d7",
        "secondary": "#d4bbff",
        "primary-fixed": "#ffdad5",
        "on-secondary": "#41008b",
        "on-tertiary": "#003061",
        "on-error-container": "#ffdad6",
        "background": "#111316",
        "on-secondary-container": "#d4baff",
        "surface-container-highest": "#333538",
        "secondary-container": "#6c04de",
        "primary": "#ffb4aa",
        "tertiary": "#a7c8ff",
        "surface-container-high": "#282a2d",
        "outline-variant": "#5e3f3b",
        "outline": "#af8782",
        "tertiary-fixed-dim": "#a7c8ff",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#d4bbff",
        "inverse-surface": "#e2e2e6",
        "primary-fixed-dim": "#ffb4aa",
        "on-surface": "#e2e2e6",
        "surface-variant": "#333538",
        "on-primary-fixed-variant": "#930007",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#5d00c2",
        "surface-container-low": "#1a1c1f",
        "surface-tint": "#ffb4aa",
        "tertiary-fixed": "#d5e3ff",
        "surface-container": "#1e2023",
        "surface-bright": "#37393d",
        "on-primary-container": "#fff7f6",
        "inverse-primary": "#c0000c",
        "on-primary-fixed": "#410001",
        "on-primary": "#690003",
        "inverse-on-surface": "#2f3034",
        "on-background": "#e2e2e6",
        "on-secondary-fixed": "#270058",
        "error-container": "#93000a",
        "on-tertiary-container": "#f8f9ff",
        "surface-container-lowest": "#0c0e11",
        "surface": "#111316",
        "on-tertiary-fixed": "#001b3c",
        "surface-dim": "#111316",
        "on-tertiary-fixed-variant": "#004689"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "xl": "40px",
        "sm": "8px",
        "margin-mobile": "16px",
        "md": "16px",
        "gutter": "16px",
        "margin-desktop": "64px",
        "xs": "4px",
        "lg": "24px"
      },
      fontFamily: {
        "be-vietnam": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
